#!/bin/sh

if [ `ln ./tests/settings.py ./settings.py` -a `ln ./tests/font.ttf ./font.ttf` ]; 
then
    cat tests/django-headline.py | python 
    rm ./*.pyc ./*.png ./settings.py ./font.ttf
else
    echo Can\`t create link to settings.py
fi
